#!/usr/bin/env python3
"""Compile one CUDA source with NVRTC and emit a C file embedding PTX and cubins.

Build-time only: needs ``nvidia-cuda-nvrtc-cu12`` (see ``make -C cuda toolchain``).
The generated C file is committed, so ordinary builds need only a C compiler and
deployed binaries need only the NVIDIA driver (``libcuda.so.1``).
"""

from __future__ import annotations

import argparse
import ctypes
import glob
from pathlib import Path
import sys

# Pascal (fleet P600 / 1050 Ti), Turing, Ampere (Merlin's 3060), Ada. PTX covers newer devices.
CUBIN_ARCHES = (61, 75, 86, 89)
PTX_ARCH = 61


def load_nvrtc():
    """Locate libnvrtc in the toolchain venv next to this script."""
    here = Path(__file__).resolve().parent
    candidates = glob.glob(str(here / ".venv/lib/python3*/site-packages/nvidia/cuda_nvrtc/lib/libnvrtc.so.12"))
    if not candidates:
        raise SystemExit("NVRTC not found; run: make -C king_hamming/cuda toolchain")
    return ctypes.CDLL(candidates[0])


def compile_image(nvrtc, source: bytes, name: bytes, arch: int, ptx: bool) -> bytes:
    """Return PTX or cubin bytes for one architecture; raise with the NVRTC log."""
    program = ctypes.c_void_p()
    if nvrtc.nvrtcCreateProgram(ctypes.byref(program), source, name, 0, None, None):
        raise RuntimeError("nvrtcCreateProgram failed")
    flag = f"--gpu-architecture={'compute' if ptx else 'sm'}_{arch}".encode()
    options = (ctypes.c_char_p * 4)(flag, b"-std=c++14", b"--use_fast_math", b"-default-device")
    status = nvrtc.nvrtcCompileProgram(program, 4, options)
    size = ctypes.c_size_t()
    nvrtc.nvrtcGetProgramLogSize(program, ctypes.byref(size))
    log = ctypes.create_string_buffer(size.value)
    nvrtc.nvrtcGetProgramLog(program, log)
    if status:
        raise RuntimeError(f"NVRTC compile failed for {flag.decode()}:\n{log.value.decode()}")
    getter, sizer = ((nvrtc.nvrtcGetPTX, nvrtc.nvrtcGetPTXSize) if ptx else
                     (nvrtc.nvrtcGetCUBIN, nvrtc.nvrtcGetCUBINSize))
    sizer(program, ctypes.byref(size))
    buffer = ctypes.create_string_buffer(size.value)
    getter(program, buffer)
    nvrtc.nvrtcDestroyProgram(ctypes.byref(program))
    return buffer.raw


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
        epilog="Example: python3 embed.py kernels.cu kh_match_images -o src/kernels_images.c")
    parser.add_argument("source", type=Path, nargs="?")
    parser.add_argument("symbol")
    parser.add_argument("-o", "--output", type=Path, required=True)
    if len(sys.argv) == 1:
        parser.print_help()
        return 0
    arguments = parser.parse_args()
    nvrtc = load_nvrtc()
    source = arguments.source.read_bytes()
    images = [(arch, False, compile_image(nvrtc, source, arguments.source.name.encode(), arch, False))
              for arch in CUBIN_ARCHES]
    images.append((PTX_ARCH, True, compile_image(nvrtc, source, arguments.source.name.encode(), PTX_ARCH, True)))
    lines = [f"// Generated by cuda/embed.py from {arguments.source.name}; do not edit.",
             '#include "kh_cuda.h"', ""]
    for index, (arch, ptx, data) in enumerate(images):
        if ptx:
            data = data.rstrip(b"\0") + b"\0"
        body = ",".join(str(byte) for byte in data)
        lines.append(f"static const unsigned char image_{index}[{len(data)}] = {{{body}}};")
    entries = ",\n    ".join(f"{{{arch}, {int(ptx)}, image_{index}, {len(data) if not ptx else len(data.rstrip(b'\0')) + 1}}}"
                             for index, (arch, ptx, data) in enumerate(images))
    lines += ["", f"const kh_cuda_image_t {arguments.symbol}[] = {{\n    {entries}\n}};",
              f"const unsigned {arguments.symbol}_count = {len(images)};", ""]
    arguments.output.write_text("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
