#ifndef KH_CUDA_H
#define KH_CUDA_H

// Minimal CUDA driver-API access through dlopen("libcuda.so.1").
// Binaries using this need no CUDA toolkit at build or run time; kernels are
// embedded as PTX/cubin images generated by cuda/embed.py.

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

typedef struct {
    unsigned arch;          // compute capability major*10+minor
    unsigned ptx;           // 1 for PTX text (JIT), 0 for cubin
    const unsigned char *data;
    size_t size;
} kh_cuda_image_t;

typedef uint64_t kh_dptr_t;

typedef struct {
    void *library;
    void *context;
    void *module;
    int device;
    unsigned arch;
    char name[128];
    uint64_t total_bytes;
    // Driver entry points (CUresult is int).
    int (*cuInit)(unsigned);
    int (*cuDeviceGet)(int *, int);
    int (*cuDeviceGetCount)(int *);
    int (*cuDeviceGetName)(char *, int, int);
    int (*cuDeviceGetAttribute)(int *, int, int);
    int (*cuDeviceTotalMem)(size_t *, int);
    int (*cuCtxCreate)(void **, unsigned, int);
    int (*cuCtxDestroy)(void *);
    int (*cuCtxSynchronize)(void);
    int (*cuModuleLoadData)(void **, const void *);
    int (*cuModuleGetFunction)(void **, void *, const char *);
    int (*cuMemAlloc)(kh_dptr_t *, size_t);
    int (*cuMemFree)(kh_dptr_t);
    int (*cuMemGetInfo)(size_t *, size_t *);
    int (*cuMemcpyHtoD)(kh_dptr_t, const void *, size_t);
    int (*cuMemcpyDtoH)(void *, kh_dptr_t, size_t);
    int (*cuMemsetD8)(kh_dptr_t, unsigned char, size_t);
    int (*cuMemsetD32)(kh_dptr_t, unsigned, size_t);
    int (*cuLaunchKernel)(void *, unsigned, unsigned, unsigned, unsigned, unsigned, unsigned,
                          unsigned, void *, void **, void **);
    int (*cuGetErrorString)(int, const char **);
} kh_cuda_t;

/*
 * Load the driver, create a context on device, and load the best embedded image.
 * Parameters: cuda: Zeroed output; device: Ordinal; images,count: Embedded kernels; error: Diagnostic.
 * Returns: True on success; false with a static or driver diagnostic.
 */
bool kh_cuda_open(kh_cuda_t *cuda, int device, const kh_cuda_image_t *images, unsigned count,
                  const char **error);

// Release the context and library; safe on a partially opened structure.
void kh_cuda_close(kh_cuda_t *cuda);

// Return a kernel handle by exported name, or NULL.
void *kh_cuda_function(kh_cuda_t *cuda, const char *name);

// Translate a driver status to text.
const char *kh_cuda_error(kh_cuda_t *cuda, int status);

/*
 * Launch a 1-D kernel and optionally synchronize.
 * Parameters: function: Kernel; blocks,threads: Launch shape; arguments: Pointers to each argument.
 * Returns: Driver status (0 is success).
 */
int kh_cuda_launch(kh_cuda_t *cuda, void *function, unsigned blocks, unsigned threads, void **arguments);

// Probe devices without loading a module: prints JSON lines {index,name,arch,total_bytes}.
int kh_cuda_probe(void);

#endif
